/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudjava;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author Ahmad Lufi A U
 */

public class CrudJava extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    public PreparedStatement pst;
   
    public CrudJava() throws Exception {
        //initComponents();
        conn = null;
        conn = DriverManager.getConnection("jdbc:mysql://localhost/java_akademik","root","");
        UpdateTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */             

    @SuppressWarnings("unchecked")
    //Generated Code                         

    private void UpdateTabel() {
        try {
            String sql = "SELECT * FROM mhs;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        String [] data = new String[6];
        int i = 1;
       
        while(rs.next()) {
            data[0] = rs.getString("nim");
            data[1] = rs.getString("nama");
            dtm.addRow(data);
            i++;
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) throws Exception{
                new CrudJava().setVisible(true);
            }

    // Variables declaration - do not modify                    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration    

}